### ISSUE TITLE
Missing description/examples with filters

### ISSUE THREAD

**Issue by BBE78** [walokra/markdown-page-generator-plugin#30]
Hi, I'm trying to use your very usefull plugin with a README.md file and include some Maven properties (such as `${project.name}`, etc...). I've seen from the configuration some parameters but they are not (yet) described on your main page.
Could you please give us some examples about the way to do it ?

Thks !

**Comment by BBE78** [comment]
After a look on the source code, I've found a way to do it:
```xml
      <plugin>
        <groupId>com.ruleoftech</groupId>
        <artifactId>markdown-page-generator-plugin</artifactId>
        <version>2.1.0</version>
        <executions>
          <execution>
            <phase>process-resources</phase>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <inputDirectory>${project.basedir}/src/main/doc</inputDirectory>
              <headerHtmlFile>${project.build.directory}/filtered-md/resources/header.html</headerHtmlFile>
              <footerHtmlFile>${project.build.directory}/filtered-md/resources/footer.html</footerHtmlFile>
              <applyFiltering>true</applyFiltering>
            </configuration>
          </execution>
        </executions>
      </plugin>
```
But some configuration parameters are not user-friendly:
1. I have to specify the header/footer files path from the filtered output dir
2. I cannot use a property that specify the `filteredOutputDirectory`: I have to specify it myself...

Some suggestions about a better way?

**Comment by walokra** [comment]
There's an example of substituting variables in header and footer files on test/substitute-project as you apparently already found.

When you use applyFiltering you can just specify the header and footer html files as you normally would, e.g. `<headerHtmlFile>${basedir}/src/main/resources/markdown/html/header.html</headerHtmlFile>`.

**Comment by alexanderchiu** [comment]
Firstly, thanks for the great plugin @walokra. 

I was trying to append the project version to the page title in my header file with
```
<title>titleToken [@project.artifactId@-@project.version@]</title>
```

I'm experiencing the same behaviour as above. Using applyFiltering, a filtered header.html appears in the filtered-md folder, but the final html files in the output directory have still have the unfiltered properties `@project.artifactId@-@project.version@`. I suspect this is due to the header file being read from the provided property https://github.com/walokra/markdown-page-generator-plugin/blob/master/src/main/java/com/ruleoftech/markdown/page/generator/plugin/MdPageGeneratorMojo.java#L475.

Judging by the name `filtered-md` I guess it wasn't intended for the html files to be filtered as well, and that's why the variables substitution support is there. Do you think this is something that would be useful as a feature? I'm happy to work on it and submit a patch.
